export default {
    COMMON_HANDLE_ERROR: 'COMMON_HANDLE_ERROR',
    COMMON_CLEAR_ERROR: 'COMMON_CLEAR_ERROR',

    COMMON_CALLBACK_ERROR: 'COMMON_CALLBACK_ERROR',
    COMMON_CALLBACK_404: 'COMMON_CALLBACK_404',
    COMMON_CALLBACK_NON_AUTH: 'COMMON_CALLBACK_NON_AUTH',

    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',

    OPEN_CONTAINER_MODAL: 'OPEN_CONTAINER_MODAL',
    CLOSE_CONTAINER_MODAL: 'CLOSE_CONTAINER_MODAL',

    TOGGLE_MENU_BAR: 'TOGGLE_MENU_BAR',

    CHANGE_WINDOW_WIDTH: 'CHANGE_WINDOW_WIDTH',
};
