'use strict';

export default {
    COMMON_SUCCESS: 'COMMON_SUCCESS',
    COMMON_ERROR: 'COMMON_ERROR',

    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',

    COMMON_REQUEST: 'COMMON_REQUEST',

    OPEN_CONTAINER_MODAL: 'OPEN_CONTAINER_MODAL',
    CLOSE_CONTAINER_MODAL: 'CLOSE_CONTAINER_MODAL',

    TOGGLE_MENU_BAR: 'TOGGLE_MENU_BAR',

    CHANGE_WINDOW_WIDTH: 'CHANGE_WINDOW_WIDTH'
}
