export default {

    REQUEST_GET_POKEMON: 'REQUEST_GET_POKEMON',
    GET_POKEMON: 'GET_POKEMON',

    REQUEST_GET_POKEMONS: 'REQUEST_GET_POKEMONS',
    GET_POKEMONS: 'GET_POKEMONS',
    PAGINATOR_POKEMONS: 'PAGINATOR_POKEMONS',

    CLEAR_POKEMONS: 'CLEAR_POKEMONS'
};
